### ISSUE TITLE
能添加进程代理吗

### ISSUE THREAD

**Issue by mingtianquan** [0x-jerry/e2fly#108]
能添加进程代理吗

**Comment by 0x-jerry** [comment]
很抱歉，短时间内不会添加此功能，因为我并不清楚如何实现这个功能。建议用其它软件代替。

**Comment by mingtianquan** [comment]
大佬你你也会go吗？  这个项目https://github.com/qtgolang/SunnyNet里面有进程代理。 不知是否能添加下vmess协议支持。本人不太会go
